debug: false
uuid: 6d296667-9f93-4995-a65d-bf1b1f67aaf0
token_id: 4apMtI48VzT8jYi5
token: 7cKPGnBq4PramgCfvhgZAy33GyJ2l8sdLYZxBjXJDsaCiyBMJapYMDRBy42RAjgq
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/mynode.ptrdctyl.my.id/fullchain.pem
    key: /etc/letsencrypt/live/mynode.ptrdctyl.my.id/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.farel.biz.id'
